name: EnchantedSpawners
version: 4.8
description: Features stackable and upgradable mob spawners and entities!
author: xMakerx/DecodedLogic

softdepend: [ASkyBlock, HolographicDisplays, Vault, WorldEdit, WorldGuard]

main: mc.decodedlogic.skybattlesuspawners.USpawners

commands:
   uspawners:
       description: Base command for EnchantedSpawners operators.
       usage: 
          - "/uspawners give <player> <entityType> <upgradeName> <amount> - Gives a specified player upgradeable spawners."
          - "/uspawners clear <radius> - Clears spawner entities in the specified radius."
          - "/uspawners inspect - Toggles spawner inspection mode"
          - "/uspawners radius 1-500 - Find nearby spawner data within a radius"

